---
# tasks file for haproxy-deploy
  - name: "install {{ lb_package }}"
    yum:
      name: "{{ lb_package }}"
      state: latest

  - name: "enable {{ lb_package }}"
    service:
      name: "{{ lb_package }}"
      state: started

  - name: "configure {{ lb_package }}"
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: "restart {{ lb_package }}"
